#include "text.h"

void displayText(string c, int size, point_t p, SDL_Plotter& g){
    int x, y;
    int count = 0;
    x = p.getX();
    y = p.getY();
    while(c[count]){
        switch (c[count]){
                case 'A': printLetter("font/A.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'B': printLetter("font/B.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'C': printLetter("font/C.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'D': printLetter("font/D.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'E': printLetter("font/E.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'F': printLetter("font/F.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'G': printLetter("font/G.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'H': printLetter("font/H.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'I': printLetter("font/I.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'J': printLetter("font/J.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'K': printLetter("font/K.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'L': printLetter("font/L.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'M': printLetter("font/M.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'N': printLetter("font/N.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'O': printLetter("font/O.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'P': printLetter("font/P.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Q': printLetter("font/Q.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'R': printLetter("font/R.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'S': printLetter("font/S.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'T': printLetter("font/T.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'U': printLetter("font/U.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'V': printLetter("font/V.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'W': printLetter("font/W.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'X': printLetter("font/X.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Y': printLetter("font/Y.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Z': printLetter("font/Z.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case ' ': printLetter("font/Space.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '!': printLetter("font/Exclamation.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '?': printLetter("font/Question.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case ',': printLetter("font/Comma.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '.': printLetter("font/Period.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 1: printLetter("font/1.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 2: printLetter("font/2.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 3: printLetter("font/3.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 4: printLetter("font/4.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 5: printLetter("font/5.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 6: printLetter("font/6.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 7: printLetter("font/7.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 8: printLetter("font/8.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 9: printLetter("font/9.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 0: printLetter("font/0.txt", x, y, size, g);
                          x += size * 10;
                          break;
        }
        count++;
    }
}

void displayScore(int a[], int size, point_t p, SDL_Plotter& g){
    int x, y;
    int count = 0;
    x = p.getX();
    y = p.getY();
    while(a[count]){
        switch (a[count]){
                case 'A': printLetter("font/A.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'B': printLetter("font/B.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'C': printLetter("font/C.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'D': printLetter("font/D.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'E': printLetter("font/E.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'F': printLetter("font/F.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'G': printLetter("font/G.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'H': printLetter("font/H.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'I': printLetter("font/I.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'J': printLetter("font/J.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'K': printLetter("font/K.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'L': printLetter("font/L.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'M': printLetter("font/M.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'N': printLetter("font/N.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'O': printLetter("font/O.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'P': printLetter("font/P.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Q': printLetter("font/Q.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'R': printLetter("font/R.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'S': printLetter("font/S.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'T': printLetter("font/T.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'U': printLetter("font/U.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'V': printLetter("font/V.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'W': printLetter("font/W.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'X': printLetter("font/X.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Y': printLetter("font/Y.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 'Z': printLetter("font/Z.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case ' ': printLetter("font/Space.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '!': printLetter("font/Exclamation.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '?': printLetter("font/Question.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case ',': printLetter("font/Comma.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case '.': printLetter("font/Period.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 1: printLetter("font/1.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 2: printLetter("font/2.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 3: printLetter("font/3.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 4: printLetter("font/4.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 5: printLetter("font/5.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 6: printLetter("font/6.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 7: printLetter("font/7.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 8: printLetter("font/8.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 9: printLetter("font/9.txt", x, y, size, g);
                          x += size * 10;
                          break;
                case 0: printLetter("font/0.txt", x, y, size, g);
                          x += size * 10;
                          break;
        }
        count++;
    }
}
